# containment-cut is MIT-licensed and the algorithm is free forever. If it saves your
# incident response time, sponsoring keeps it maintained. Pro licenses (live tenant
# import, gated execution, multi-objective optimisation) are the other way to support
# it — see docs/pro.md.
github: [earbona23]
patreon: EduardArbona
